import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;

import java.io.FileOutputStream;

public class ReportGenerator {

    public static void generateReport(
            Candidate candidate,
            Job job,
            ScreeningResult result,
            String outputFile) {

        try {

            Document document = new Document();

            PdfWriter.getInstance(document, new FileOutputStream(outputFile));

            document.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            Font headingFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);
            Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 12);

            document.add(new Paragraph("AI RESUME SCREENING REPORT", titleFont));
            document.add(new Paragraph(" "));

            document.add(new Paragraph("Candidate Details", headingFont));
            document.add(new Paragraph("Name : " + candidate.getName(), normalFont));
            document.add(new Paragraph("Email : " + candidate.getEmail(), normalFont));
            document.add(new Paragraph("Phone : " + candidate.getPhone(), normalFont));
            document.add(new Paragraph("Skills : " + candidate.getSkills(), normalFont));
            document.add(new Paragraph("Experience : " + candidate.getExperience(), normalFont));

            document.add(new Paragraph(" "));

            document.add(new Paragraph("Job Details", headingFont));
            document.add(new Paragraph("Job Title : " + job.getTitle(), normalFont));
            document.add(new Paragraph("Description : " + job.getDescription(), normalFont));

            document.add(new Paragraph(" "));

            document.add(new Paragraph("AI Screening Result", headingFont));
            document.add(new Paragraph("Score : " + result.getScore(), normalFont));
            document.add(new Paragraph("Recommendation : " + result.getRecommendation(), normalFont));
            document.add(new Paragraph("Remarks : " + result.getRemarks(), normalFont));

            document.add(new Paragraph(" "));
            document.add(new Paragraph("Generated by AI Resume Screening System"));

            document.close();

            System.out.println("PDF Report Generated Successfully.");

        } catch (Exception e) {

            e.printStackTrace();

        }
    }
}